### ISSUE TITLE
Need loading screen

### ISSUE THREAD

**Issue by iratahack** [iratahack/CastleEscape#9]
Looking for an artist to creat a loading screen in png format which can be converted to scr format with https://github.com/MatejJan/PNG-to-SCR

**Comment by jardafis** [comment]
I can draw loading screen in ZX Paintbrush.

**Comment by iratahack** [comment]
@jardafis, Thanks for reaching out. Please open a pull request against CastleEscape/assets/title.png with your loading screen candidates.
